# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: Quartet Data Portal Docs
site_description: 'Quality Control and Data Integration of Multi-omics Profiling'
site_author: 'Jingcheng Yang'
announce: 'Quartet Team'
announce_text: 'a development version has been released on <a href="https://dev.chinese-quartet.org" target="_blank">https://dev.chinese-quartet.org</a>'
docs_dir: docs/
repo_name: 'chinese-quartet'
repo_url: 'https://github.com/chinese-quartet'
edit_uri: docs.chinese-quartet.org/edit/master/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date
extra:
  homepage: https://chinese-quartet.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chinese-quartet
      name: Chinese Quartet
  generator: false
copyright: Copyright &copy; 2016 - 2022 Quartet Team
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
      repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
  name: 'material'

# Table of contents
nav:
  - Home: index.md
  - 'Getting Started':
    - Overview: getting_started/introduction.md
    - Toolbars: getting_started/toolbars.md
    - 'Register Account': getting_started/register_account.md
    - 'Request Reference Materials': getting_started/request_reference_materials.md
    - 'Access Quartet MultiOmics Data': getting_started/request_omics_data.md
    - 'Analyze Your Data':
      - 'Quality Assessment Page': getting_started/quality_assessment_page.md
      - 'Submit Data': getting_started/submit_data.md
      - 'Select Pipeline': getting_started/select_pipeline.md
      - 'Generate QC Report': getting_started/qc_report.md
      - 'Analysis History': getting_started/analysis_history.md
    - 'Explore Reference Datasets':
      - 'Browser and Download': getting_started/browser_and_download.md
      - 'Interactive Visualization': getting_started/interactive_visualization.md
  - 'Data & Pipelines':
    - Genomcis: 
      - 'Introduction': data_pipelines/genomics/intro.md
      - 'Metadata Template': data_pipelines/genomics/metadata_template.md
      - 'Omics Data Format': data_pipelines/genomics/omics_data_format.md
      - 'Analysis Pipeline': data_pipelines/genomics/analysis_pipeline.md
      - 'QC Report': data_pipelines/genomics/qc_report.md
    - Transcriptomics:
      - 'Introduction': data_pipelines/transcriptomics/intro.md
      - 'Metadata Template': data_pipelines/transcriptomics/metadata_template.md
      - 'Omics Data Format': data_pipelines/transcriptomics/omics_data_format.md
      - 'Analysis Pipeline': data_pipelines/transcriptomics/analysis_pipeline.md
      - 'QC Report': data_pipelines/transcriptomics/qc_report.md
    - Proteomics:
      - 'Metadata Template': data_pipelines/proteomics/metadata_template.md
      - 'Omics Data Format': data_pipelines/proteomics/omics_data_format.md
      # - 'Analysis Pipeline': data_pipelines/proteomics/analysis_pipeline.md
      - 'QC Report': data_pipelines/proteomics/qc_report.md
    - Metabolomics:
      - 'Metadata Template': data_pipelines/metabolomics/metadata_template.md
      - 'Omics Data Format': data_pipelines/metabolomics/omics_data_format.md
      # - 'Analysis Pipeline': data_pipelines/metabolomics/analysis_pipeline.md
      - 'QC Report': data_pipelines/metabolomics/qc_report.md
  - Tools: 
    - 'Data Repo': tools/data_repo.md
    - 'Data Transfer Tools':
      - 'Data Transfer Tool Command Line Documentation': tools/ossutil.md
      - 'Data Transfer Tool UI Documentation': tools/ossbrowser.md
    - 'Data Analysis Tools':
      - 'Choppy App': tools/choppy_apps.md
      - 'MultiReport': tools/multireport.md
    - 'Visualization Tools': tools/visualization_tools.md
  # - 'Data Dictionary':
  #   - About: data_dictionary/about.md
  #   - 'How to Prepare Your Metadata?': data_dictionary/metadata.md
  #   - 'Release Notes': data_dictionary/release_notes.md
  - About:
    - News: about/news.md
    - Publications: about/publications.md
    - Quartet Team: about/members.md
    - Collaborators: about/collaborators.md
    - Policies: about/policies.md
    - FAQs: about/faqs.md
  # - Developers:
  #   - News: developers/changelog.md