# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: Quartet Data Portal
site_description: 'Quality Control and Data Integration of Multi-omics Profiling'
site_author: 'Jingcheng Yang'
announce: 'Quartet Team'
announce_text: 'a development version has been released on <a href="https://dev.chinese-quartet.org" target="_blank">https://dev.chinese-quartet.org</a>'
docs_dir: docs/
repo_name: 'chinese-quartet'
repo_url: 'https://github.com/chinese-quartet'
edit_uri: docs.chinese-quartet.org/edit/master/docs/
nav:
  - Home: index.md
  - 'Getting Started': getting_started.md
  - Users: 
    - FAQs: users/faqs.md
    - News: users/news.md
    - 'Request Reference Materials': users/request_reference_materials.md
    - 'Request Omics Data': users/request_omics_data.md
    - 'Register Account': users/register_account.md
    - 'Analyze Customized Data': users/analyze_customized_data.md
    - 'How to Prepare Your Metadata?': users/metadata.md
  - Developers:
    - News: developers/changelog.md
markdown_extensions:
  - meta
extra_css:
  - stylesheets/extra.css
plugins:
  - search
extra:
  homepage: https://chinese-quartet.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chinese-quartet
      name: Chinese Quartet
  generator: false
copyright: Copyright &copy; 2016 - 2022 Quartet Team
theme:
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
      repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
  name: 'material'