site_name: Chinese Quartet
site_description: 'A docs test'
site_author: 'Jingcheng Yang'
docs_dir: docs/
repo_name: 'chinese-quartet/docs.chinese-quartet.org'
repo_url: 'https://github.com/chinese-quartet/docs.chinese-quartet.org'
nav:
  - Home: index.md
theme:
  name: 'material'