# Please access https://squidfunk.github.io/mkdocs-material for more details.
site_name: Quartet Data Portal
site_description: 'Quality Control and Data Integration of Multi-omics Profiling'
site_author: 'Jingcheng Yang'
announce: 'Quartet Team'
announce_text: 'a development version has been released on <a href="https://dev.chinese-quartet.org" target="_blank">https://dev.chinese-quartet.org</a>'
docs_dir: docs/
repo_name: 'chinese-quartet'
repo_url: 'https://github.com/chinese-quartet'
edit_uri: docs.chinese-quartet.org/edit/master/docs/
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
extra:
  homepage: https://chinese-quartet.org
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chinese-quartet
      name: Chinese Quartet
  generator: false
copyright: Copyright &copy; 2016 - 2022 Quartet Team
theme:
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
  logo: assets/images/logo.png
  icon:
      repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
  name: 'material'

# Table of contents
nav:
  - Home: index.md
  - 'Getting Started':
    - Introduction: getting_started/introduction.md
    - FAQs: getting_started/faqs.md
    - News: getting_started/news.md
    - 'Request Reference Materials': getting_started/request_reference_materials.md
    - 'Request Omics Data': getting_started/request_omics_data.md
    - 'Register Account': getting_started/register_account.md
    - 'Analyze Customized Data':
      - 'Genomics Data': getting_started/pipelines/genomics.md
      - 'Transcriptomics Data': getting_started/pipelines/transcriptomics.md
      - 'Proteomics Data': getting_started/pipelines/proteomics.md
      - 'Metabolomics Data': getting_started/pipelines/metabolomics.md
  - 'Data File & Pipelines':
    - Introduction: data_files/introduction.md
  - Tools: 
    - Introduction: tools/index.md
    - 'Data Transfer Tool Command Line Documentation': tools/ossutil.md
  - 'Data Dictionary':
    - About: data_dictionary/about.md
    - 'How to Prepare Your Metadata?': data_dictionary/metadata.md
    - 'Release Notes': data_dictionary/release_notes.md
  - Developers:
    - News: developers/changelog.md